"""empty message

Revision ID: 8753ec68f3ec
Revises: 556dd1d3d19e
Create Date: 2021-12-15 15:09:37.435806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8753ec68f3ec'
down_revision = '556dd1d3d19e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'image')
    # ### end Alembic commands ###
