"""empty message

Revision ID: 556dd1d3d19e
Revises: f9cb7f76d08b
Create Date: 2021-11-18 11:45:03.217395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556dd1d3d19e'
down_revision = 'f9cb7f76d08b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower', sa.Integer(), nullable=False),
    sa.Column('followed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    # ### end Alembic commands ###
