"""empty message

Revision ID: b37f56b1225e
Revises: e32d30d9c5d7
Create Date: 2021-11-16 15:28:43.582097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b37f56b1225e'
down_revision = 'e32d30d9c5d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('question', sa.String(length=255), nullable=False))
    op.alter_column('questions', 'body',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('questions', 'title')
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('questions', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('questions', 'body',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('questions', 'question')
    # ### end Alembic commands ###
